#!/usr/local/bin/python
# -*- coding: UTF-8 -*-

#bibliography.py


"""A full bibliography of everything Charles Dickens ever wrote.

Used when creating titles using Markov chains.

Sources:
    -   https://www.charlesdickensinfo.com/novels/complete-works/
    -   http://www.dickens-online.info/charles-dickens-bibliography.htm
    -   https://en.wikipedia.org/wiki/Charles_Dickens_bibliography
    -   https://www.biblio.com/charles-dickens/author/3    
"""



# 367 publications listed.

publications = [


	"A Budget Of Christmas Tales",
	"A Child's Dream Of a Star",
	"A Child's Dream of a Star",
	"A Child's History Of England",
	"A Child's History of England",
	"A Childs History of England",
	"A Christmas Carol",
	"A Christmas Carol Deluxe",
	"A Christmas Carol In Prose",
	"A Christmas Carol In Prose Being a Ghost Story Of Yule-Tide",
	"A Christmas Carol In Prose, Being a Ghost Story Of Christmas",
	"A Christmas Carol In Prose, Being a Ghost Story Of Yule-Tide",
	"A Christmas Carol and Other Christmas Books",
	"A Christmas Carol and Other Christmas Stories",
	"A Christmas Carol and Other Christmas Writings",
	"A Christmas Carol and Other Haunting Tales",
	"A Christmas Carol and Other Holiday Tales",
	"A Christmas Carol and Other Short Stories",
	"A Christmas Carol and Other Stories",
	"A Christmas Carol and The Cricket On the Hearth",
	"A Christmas Carol and Two Other Christmas Books",
	"A Christmas Carol in Prose Being a Ghost Story of Christmas",
	"A Christmas Carol, Being a Ghost Story Of Christmas",
	"A Christmas Carol, a Ghost Story Of Christmas",
	"A Christmas Carol, and The Chimes",
	"A Christmas Dinner",
	"A Christmas Tree",
	"A Coal Miner's Evidence",
	"A Dinner at Poplar Walk",
	"A Flight",
	"A Ghost in the Bride's Chamber",
	"A Holiday Romance",
	"A House To Let",
	"A House to Let",
	"A Lion",
	"A Madman's Manuscript",
	"A Message From the Sea",
	"A Message from the Sea",
	"A Plated Article",
	"A Pottery Story",
	"A Rosy Path",
	"A Round Of Stories By the Christmas Fire",
	"A Tale Of Two Cities",
	"A Tale Of Two Cities a Story Of the French Revolution",
	"A Tale Of Two Cities, Complete and Unabridged",
	"A Tale of Two Cities",
	"All The Year Round",
	"All the Year Round",
	"American Notes",
	"American Notes For General Circulation",
	"American Notes: For General Circulation",
	"An Account Of a Wedding",
	"An Account Of a Wedding, Excerpts From the Pickwick Papers",
	"Another Round Of Stories By the Christmas Fire",
	"Barnaby Rudge",
	"Barnaby Rudge, a Tale Of the Riots Of '80",
	"Barnaby Rudge, a Tale Of the Riots Of Eighty",
	"Baron Of Grogzwig",
	"Beautiful Stories About Children",
	"Bentley's Miscellany",
	"Best Ghost Stories",
	"Bleak House",
	"Bleak House or Poor Jo",
	"Book Of Memoranda",
	"Boots At the Holly Tree Inn",
	"Boots At the Holly-Tree Inn and Other Stories",
	"Boots at the Holly-tree Inn: And Other Stories",
	"Captain Boldheart",
	"Captain Boldheart and The Latin-Grammar Master",
	"Captain Boldheart the Magic Fishbone",
	"Captain Grant's Children",
	"Captain Murderer",
	"Children Stories",
	"Chops the Dwarf",
	"Christmas At Dingley Dell",
	"Christmas Books",
	"Christmas Eve With the Spirits",
	"Christmas Ghost Stories",
	"Christmas Short Stories",
	"Christmas Spirits",
	"Christmas Stories",
	"Christmas Tales",
	"Christmas Tales Of Fantasy",
	"Complete Ghost Stories",
	"Complete Works",
	"Courts Of Europe",
	"David Cooperfield",
	"David Coperfield",
	"David Copperfield",
	"David Copperfield a Reading In Five Chapters",
	"David Copperfield the Younger",
	"Dealings With the Firm Of Dombey and Son",
	"Dealings With the Firm Of Dombey and Son Wholesale, Retail and For Exportation",
	"December Vision",
	"Dialogues From Dickens",
	"Dictionary Of London",
	"Dictionary Of London 1888",
	"Dictionary Of London, 1885",
	"Dictionary Of Paris",
	"Dictionary Of Paris, 1882 an Unconventional Handbook",
	"Dictionary Of the Thames",
	"Dictionary Of the Thames, 1887",
	"Doctor Marigold",
	"Doctor Marigold's Prescriptions",
	"Dombey and Son",
	"Dombey and Sons",
	"Dominoes",
	"Dr Blimber's School",
	"Drawn From Life",
	"Dreadful Almanac",
	"Edwin Drood",
	"Florence Dombey",
	"Four Complete Novels",
	"Four Novels",
	"Frauds on the Fairies",
	"Frozen Deep",
	"George Silverman's Explanation",
	"George Silvermans Explanation",
	"Ghostly Christmas",
	"Going Into Society",
	"Going into Society",
	"Great Expectaions",
	"Great Expectatations",
	"Great Expectations",
	"Hard Times",
	"Hard Times For These Times",
	"Haunted Man and The Ghost's Bargain",
	"Holiday Romance",
	"Holiday Tales",
	"Holly Berries",
	"Household Words",
	"Hunted Down",
	"Hunted Down: The Detective Stories of Charles Dickens",
	"In Memoriam W. M. Thackeray the first!",
	"Inspector Bucket's Job",
	"Is She His Wife",
	"Is She His Wife or Something Singular",
	"John Jasper's Secret",
	"Landor's Life",
	"Lazy Tour Of Two Idle Apprentices",
	"Letters of Charles Dickens to Wilkie Collins",
	"Life and Adventures Of Martin Chuzzlewit",
	"Life and Adventures Of Nicholas Nickelby",
	"Life's Little Handbook Of Wisdom",
	"Little Dorrit",
	"Little Dorritt",
	"Little Nell",
	"Little Nell From the Old Curiosity-Shop",
	"Little Paul Domby",
	"Magic Fishbone",
	"Martin Chuzzlewit",
	"Master Humphrey's Clock",
	"Miscellaneous Papers",
	"Miscellaneous Tales",
	"Miscellaneous Tales, and Sketches",
	"Mr Nightingale's Diary",
	"Mr Pickwick",
	"Mr Pickwick's Christmas",
	"Mrs Gamp",
	"Mrs Lirriper",
	"Mrs Lirriper and Other Stories",
	"Mrs Lirriper's Legacy",
	"Mrs Lirriper's Lodgings",
	"Mrs LirriperS Lodgings",
	"Mrs Orange",
	"Mrs. Lirriper's Legacy",
	"Mrs. Lirriper's Lodgings",
	"Mudfog and Other Sketches",
	"Mugby Junction",
	"Mugby Junction and Other Stories",
	"Murder and Mystery",
	"My Early Times",
	"Nell and Her Grandfather",
	"Nicholas Nickelby",
	"Nicholas Nickleby",
	"Nicolas Nickleby",
	"Night Walks",
	"Nikolaus Nickleby",
	"No Thoroughfare",
	"Nobody's Story",
	"Old Curiosity Shop",
	"Old Lamps For New Ones",
	"Old Lamps For New Ones and Other Sketches and Essays",
	"Old Lamps For New Ones and Other Sketches and Essays Hitherto Uncollected",
	"Old Lamps For New Ones and Other Sketches and Essays, Hitherto Uncollected",
	"Oliver Twist",
	"Oliver Twist Or, the Parish Boy's Progress",
	"Oliver Twist, Complete and Unabridged",
	"Oliver Twist; or, The Parish Boy's Progress",
	"Olivier Twist",
	"On London",
	"On Poverty",
	"On Travel",
	"One Dinner a Week and Travels In the East",
	"Our English Watering-Place",
	"Our Mutual Friend",
	"Our Mutual Friends",
	"Paul Dombey",
	"Pearl-Fishing",
	"Pickwick Club",
	"Pickwick Papers",
	"Pickwick Papers the Posthumous Papers Of the Pickwick Club",
	"Pictures From Italy",
	"Pictures from Italy",
	"Prince Bull",
	"Public Life Of Mr. Tulrumble",
	"Public Life of Mr. Trumble, Once Mayor of Mudfog",
	"Reprinted Pieces",
	"Scenes Of London Life",
	"Sketches",
	"Sketches By Boz",
	"Sketches By Boz Illustrative Of Every-Day Life and Every-Day People",
	"Sketches Of Young Couples",
	"Sketches Of Young Gentlemen",
	"Sketches Of Young Gentlemen and Young Couples",
	"Sketches Of Young Gentlemen, Dedicated To the Young Ladies",
	"Sketches by Boz",
	"Sketches of Young Couples",
	"Sketches of Young Gentlemen",
	"Some Christmas Stories",
	"Some Short Christmas Stories",
	"Somebody's Luggage",
	"Something Singular",
	"Speeches, Letters and Sayings",
	"Speeches: Literary and Social",
	"Stories From the Christmas Numbers",
	"Sunday Under Three Heads",
	"Sunday under Three Heads",
	"Tale Of 2 Cities",
	"The Adventures Of Oliver Twist",
	"The Adventures of Oliver Twist",
	"The Bagman's Story",
	"The Baron of Grogzwig",
	"The Battle Of Life",
	"The Battle Of Life - a Love Story",
	"The Battle of Life",
	"The Begging-Letter Writer",
	"The Child Wife",
	"The Child's Story",
	"The Childhood Of David Copperfield",
	"The Children's David Copperfield",
	"The Chimes",
	"The Chimes a Goblin Story",
	"The Chimes a Goblin Story Of Some Bells That Rang an Old Year Out and A New Year In",
	"The Chimes: A Goblin Story",
	"The Christmas Books",
	"The Christmas Stories",
	"The Complete Poems of Charles Dickens",
	"The Cricket On the Hearth",
	"The Cricket On the Hearth a Fairy Tale Of Home",
	"The Cricket on the Hearth",
	"The Cricket on the Hearth: A Fairy Tale of Home",
	"The D Case",
	"The Daily News",
	"The Fine Old English Gentleman",
	"The First Meeting of Mudfog",
	"The Frozen Deep",
	"The Ghosts of the Mail",
	"The Goblins Who Stole A Sexton",
	"The Goblins who Stole a Sexton",
	"The Haunted House",
	"The Haunted Man",
	"The Haunted Man and The Ghost's Bargain",
	"The Haunted Man and The Ghosts Bargin",
	"The Haunted Man and the Ghost's Bargain",
	"The Holly Tree",
	"The Holly Tree Inn",
	"The Holly-Tree",
	"The Holly-Tree Inn",
	"The Holly-Tree and Other Christmas Stories",
	"The Holly-tree Inn",
	"The Household Narrative Of Current Events",
	"The Illustrated Life Adventures Of Nicholas Nickleby",
	"The Lamplighter",
	"The Lamplighter's Story",
	"The Late Mr. Stanfield",
	"The Lazy Tour of Two Idle Apprentices",
	"The Life Adventures Of Martin Chuzzlewit",
	"The Life Of Our Lord",
	"The Life Of Our Lord Written Expressly For His Children",
	"The Life Of Our Lord Written For His Children During the Years 1846-1849",
	"The Life and Adventures Of Martin Chuzzlewit",
	"The Life and Adventures Of Martin Chuzzlewit His Relatives Friends and Enemies",
	"The Life and Adventures Of Nicholas Nickleby",
	"The Life and Adventures of Martin Chuzzlewit",
	"The Life and Adveture",
	"The Life of Our Lord",
	"The Life of Our Lord: As written for his children",
	"The Long Voyage",
	"The Lost Arctic Voyagers",
	"The Loving Ballad Of Lord Bateman",
	"The Manuscript Of Great Expectations",
	"The Mudfog Papers",
	"The Mudfog Papers Etc Now First Collected",
	"The Mudfog Papers, Etc",
	"The Mudfrog Papers",
	"The Mystery Of Edwin Drood",
	"The Mystery of Edwin Drood",
	"The Old Curiosity Shop",
	"The Old Curiousity Shop",
	"The Pantomime of Life",
	"The Perils Of Certain English Prisoners",
	"The Perils of Certain English Prisoners",
	"The Personal History Of David Copperfield",
	"The Personal History and Experience Of David Copperfield",
	"The Personal History and Experience Of David Copperfield the Younger",
	"The Personal History, Adventures, Experience Observation Of David Copperfield the Younger Of Blunderstone Rookery",
	"The Personal History, Experience and Observation Of David Copperfield",
	"The Pickwick Papers",
	"The Pickwick Papers, Vol 1",
	"The Pickwick Papers, Volume II",
	"The Poor Man and his Beer",
	"The Poor Relation's Story",
	"The Poor Traveller",
	"The Posthumous Papers",
	"The Posthumous Papers Of the Pickwick Club",
	"The Posthumous Papers Of the Pickwick Club Vol 1",
	"The Posthumous Papers Of the Pickwick Club Volume II",
	"The Posthumous Papers Of the Pickwick Club, Volume 1",
	"The Posthumous Papers Of the Pickwick Club, Volume 2",
	"The Posthumous Papers Of the Pickwick Club, Volume 3",
	"The Posthumous Papers Of the Pickwick Club, Volume I",
	"The Posthumous Papers Of the Pickwick Papers",
	"The Posthumous Papers of the Pickwick Club",
	"The Postumous Papers Of the Pickwick Club",
	"The Public Readings",
	"The Queer Chair",
	"The Schoolboy's Story",
	"The Seven Poor Travelers",
	"The Seven Poor Travellers",
	"The Signal Man",
	"The Signal-Man",
	"The Signalman",
	"The Signalman Other Ghost Stories",
	"The Story Of Little Dombey",
	"The Story Of Little Nell",
	"The Story Of Oliver Twist",
	"The Story Of Richard Doubledick",
	"The Story Of the Bagman's Uncle",
	"The Story of the Goblins Who Stole a Sexton",
	"The Strange Gentleman",
	"The Trial For Murder",
	"The Trial Of William Tinkling",
	"The Trial for Murder",
	"The Uncommercial Traveler",
	"The Uncommercial Traveller",
	"The Village Coquettes",
	"The Wedding Bells",
	"The World Here and There",
	"The Wreck Of the Golden Mary",
	"The Wreck of the Golden Mary",
	"The posthumous papers of the Picwick club",
	"Thousand and One Humbugs",
	"Three Short Stories",
	"To Be Read At Dusk",
	"To be Read at Dusk",
	"Tom Tiddler's Ground",
	"Travelling Abroad",
	"Twice-Told Tales",
	"Two Boxes Of Gold",
	"Two Boxes Of Gold and Other Stories",
	"What Christmas Is As We Grow Older",
	"What Christmas Is As We Grow Older, and Other Stories",
	"What Christmas is, as We Grow Older",
	"Wreck of the Golden Mary",
	"a Tale Of Two Cities",
	"the Chimes",
	]

# END OF FILE

